spring.application.name=server

# 공통 설정
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

allowedOrigins=chrome-extension://jdkkfkhplhefncpgikdfckfgibbnlhip

hash-secret=1234567890123456

IMP_KEY=0703144577843651
IMP_SECRET=WbE3MJB4QOslehxEJEjGzPN3myjaL00KShO7JS5tTlnf9FnwZhFpLsmUkkEid2RIHVE2xvJ6v8UEmizY

IMP_ID=imp87733501
channelKey=channel-key-44d3eb06-438a-4bbe-8e91-bc7c80c3fa29

spring.profiles.active=local