spring.application.name=server

# DB 연동
spring.datasource.url=jdbc:mysql://localhost:3306/tabbook?serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=asd14825@

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

allowedOrigins=chrome-extension://jdkkfkhplhefncpgikdfckfgibbnlhip

redirectUrl=http://localhost:8080/

hash-secret=1234567890123456

IMP_KEY=0703144577843651
IMP_SECRET=WbE3MJB4QOslehxEJEjGzPN3myjaL00KShO7JS5tTlnf9FnwZhFpLsmUkkEid2RIHVE2xvJ6v8UEmizY

IMP_ID=imp87733501
channelKey=channel-key-44d3eb06-438a-4bbe-8e91-bc7c80c3fa29